export const AppConstants = {
  BASE_IMAGE_PATH: 'https://image.tmdb.org/t/p/w500',
  LANDING_IMAGE: require('assets/landing.png'),
};

export const AppIcons = {
  Search: 'magnify',
  Options: 'dots-vertical',
  UserLogo: 'account-circle',
  UserName: 'account',
  UserSettings: 'account-cog',
  LightMode: 'weather-sunny',
  DarkMode: 'moon-waning-crescent',
  Help: 'help-circle',
  LogOut: 'logout',
  BackButton: 'arrow-left',
  Favorite: 'heart',
  Favorite_Outline: 'heart-outline',
  Email: 'email',
  Password: 'lock',
  PasswordHidden: 'eye-off',
  PasswordVisible: 'eye',
  Language: 'translate',
};

export const colors = {
  dark: {
    background: '#121212',
    text: '#F3F3F3',
    primary: '#32a873',
    secondary: '#F3F3F3',
    placeholder: '#F3F3F3',
    signupLink: '#95acff',
    outlineColor: '#F3F3F3',
    inputBackground: '#1e1e1e',
    tabBarBackground: '#121212',
    tabBarBorderTop: '#121212',
    tabBarInactive: '#8E8E93',
    tabBarActive: '#00C853',
    border: 'rgba(0, 0, 0, 0.25)',
    secondaryText: '#969696',
    errorColor: '#FF0000',
  },
  light: {
    background: '#ffffff',
    text: '#121212',
    primary: '#32a873',
    secondary: '#121212',
    placeholder: '#121212',
    signupLink: '#0066cc',
    outlineColor: '#cccccc',
    inputBackground: '#f3f3f3',
    tabBarBackground: '#FFFFFF',
    tabBarBorderTop: '#E0E0E0',
    tabBarInactive: '#8E8E93',
    tabBarActive: '#00C853',
    border: 'rgba(0, 0, 0, 0.25)',
    secondaryText: '#969696',
    errorColor: '#FF0000',
  },
};
