export const CategoryTitles = {
  popular: 'Popular',
  nowPlaying: 'Now Playing',
  upcoming: 'Upcoming',
  topRated: 'Top Rated',
};

export const AppConstants = {
  BASE_IMAGE_PATH: 'https://image.tmdb.org/t/p/w500',
  LANDING_IMAGE: require('assets/landing.png'),
  SEARCH_TITLE: 'Search',
  SEARCH_PLACEHOLDER: 'Search for a title...',
  FAVORITES_TITLE: 'Favorites',
  NO_FAVORITES_MESSAGE: 'No favorites added yet!',
  NO_FAVORITES_SUB_MESSAGE:
    'Add some movies to your favorites list to see them here.',
  FAVORITES_DOWNLOAD_BADGE: 'Downloaded',
  SETTINGS_TITLE: 'Settings',
  PROFILE_NAME: 'Worlder',
  PROFILE_EMAIL: 'worlder@wolonote.com',
  ACCOUNT_TEXT: 'Account',
  CHANGE_APPEARANCE_TEXT: 'Change Appearance',
  HELP_TEXT: 'Help',
  LOGOUT_TEXT: 'Logout',
  LOADING_TEXT: 'Loading...',
  GENRES_LABEL: 'Genres:',
  RATING_LABEL: 'Rating:',
  LOGIN_TITLE: 'Login',
  EMAIL_LABEL: 'Email',
  PASSWORD_LABEL: 'Password',
  USERNAME_LABEL: 'Username',
  EMAIL_REQUIRED_ERROR: 'Email is required',
  EMAIL_INVALID_ERROR: 'Please enter a valid email',
  PASSWORD_REQUIRED_ERROR: 'Password is required',
  USERNAME_REQUIRED_ERROR: 'Username is required',
  PASSWORD_LENGTH_ERROR: 'Password must be at least 6 characters',
  LOGIN_FAILURE_MESSAGE: 'Invalid Credentials',
  SIGNUP_PROMPT: 'Haven’t made an account?',
  LOGIN_PROMPT: 'Already have an account?',
  SIGNUP_LINK_TEXT: 'Sign Up',
  SIGNUP_SUCCESS: 'User Created Successfully',
  REGISTRATION_FAILED_ERROR: 'Registration Failed',
  MOVIE_DETAILS_FETCH_ERROR: 'Failed to fetch movie details',
};

export const AppIcons = {
  Search: 'magnify',
  Options: 'dots-vertical',
  UserLogo: 'account-circle',
  UserName: 'account',
  UserSettings: 'account-cog',
  LightMode: 'weather-sunny',
  DarkMode: 'moon-waning-crescent',
  Help: 'help-circle',
  LogOut: 'logout',
  BackButton: 'arrow-left',
  Favorite: 'heart',
  Favorite_Outline: 'heart-outline',
  Email: 'email',
  Password: 'lock',
  PasswordHidden: 'eye-off',
  PasswordVisible: 'eye',
};
